### ISSUE TITLE
Image Decode Quality always selects slow,high quality

### ISSUE THREAD

**Issue by quroe** [8cAyqpVKio/cnxd#3]
`設定＞イメージ表示画面の設定＞Jpeg展開の画質`がどちらを選択しても`画質を優先する`の表示になる

**Comment by 8cAyqpVKio** [comment]
[refactor: jpeg decoder](https://github.com/8cAyqpVKio/cnxd/commit/0a69c8f8ad6a68431d84e6a7e70c84a14f759f0d)にて、libjpeg-turboのアップグレードに伴うJPEGデコード実装の最適化を実施しました。
「Jpeg展開の画質」オプションはデコード実装の最適化の際に廃止され、デフォルトでDCTの計算レベルがFASTに設定されるようになります。

[refactor: remove unused option](https://github.com/8cAyqpVKio/cnxd/commit/09a4c5a9e5c862de441aa2f7805a6ecfb3905234)にて、「Jpeg展開の画質」オプションは完全に削除されます。
